### ISSUE TITLE
DataFetchingEnvironment Arguments are null on Resolvers

### ISSUE THREAD

**Issue by senzzzi** [graphql-java/graphql-spring-boot#100]
When I set an argument like `dataFetchingEnvironment.getArguments.put("foo", "bar")` and try to get this arguments on a GraphQLResolver function that receives the DataFetchingEnvironment, the arguments are empty. I am not sure, but I think this was working in a previous version.

**Comment by rpmcdougall** [comment]
Do you have an example of a resolver you have implemented where you are observing this behavior?

**Comment by senzzzi** [comment]
The example would be more or less like this. So, on the class that implements the GraphQLQueryResolver, on some queries, I set some arguments on the DataFetchingEnvironment. Then, on Resolvers like this (running the same query), the arguments on dataFetchingEnvironment object are empty. As a workaround, I am using attributes inside the HttpServletRequest on the same DataFetchingEnvironment.

`public class RaceResolver implements GraphQLResolver<Race> {

public String getId(Race race, DataFetchingEnvironment dataFetchingEnvironment) {
        return race.getTrack().getCode().concat(race.getNumber());
    }

}
`

**Comment by rpmcdougall** [comment]
When you experience the issue, is your entire datrafetechingenvironment null? I've run into this recently as well and I'm not sure why its not getting passed in.

**Comment by senzzzi** [comment]
@rpmcdougall. The Datafetchingenvironment object looks ok to me. All fields have the values they are supposed to. But the arguments are empty, even though I put a key/value pair on it.

**Comment by oliemansm** [comment]
@senzzzi So in the `GraphQLQueryResolver` you do something like this:
```java
public Race getRace(DataFetchingEnvironment environment) {
  environment.getArguments().put("key", "value");
  return new Race();
}
```
And then in `RaceResolver` you want to do something like this:
```java
public String getId(Race race, DataFetchingEnvironment environment) {
  String value = environment.getArgument("key");
  // ... do something with value
  return race.getId();
}
```
I'm not too familiar with the `DataFetchingEnvironment` myself, but since it doesn't have any actual setters, I'm wondering if this is really the intended way to work with that object. What if they decide to make it immutable at some point? You don't have any guarantee that the `getArguments` actually gives you access to the `arguments` map inside the `environment`. It might as well give you a defensive copy.

What kind of information are you trying to exchange? Wouldn't it be appropriate to be part of `Race` itself? For example a call like `race.setKey("value")`. If you could elaborate a bit on your actual use case we might come up with an alternate solution.

This is actually more an issue for either `graphql-java-tools` or `graph-java` btw.

**Comment by senzzzi** [comment]
@oliemansm I understand when you say that this could be part of `Race `. But this arguments are not really a part of Race, let's say that this varies according to the request. Depending on some request field, I might need to resolve these fields differently (e.g, go to different Datasources, apply different formats to those fields, etc). 

I also agree that this is probably an issue on one of those libraries and not this starter library.

**Comment by oliemansm** [comment]
@senzzzi How does the request actually differ in those cases then? Do you mean it depends on one of the parameters of the query? I'm apparently missing something here to fully understand what you mean :-)

**Comment by senzzzi** [comment]
This was not an issue, I got help on graphql-java repo: [.](https://github.com/graphql-java/graphql-java/issues/1245) I think this can be closed

**Comment by oliemansm** [comment]
Ok, thanks
