### ISSUE TITLE
2 graphql servlets

### ISSUE THREAD

**Issue by rolandkozma** [graphql-java/graphql-spring-boot#29]
I'd like to be able to start 2 or more graphql servlets on different paths. This way I'd be able to configure different security settings per servlet with spring security (e.g. give public access to one while secure the other). Is this a reasonable request?

the config would look like:

graphql:
  servlet:
    mapping: /graphql, /graphql2

Thanks,
- Roland

**Comment by oliemansm** [comment]
I wouldn't configure Spring Security on servlets like that, but annotate the actual service methods that are being called by the GraphQL resolvers. That way you can authorize differently per query or mutation level, and filter response objects based on the principal.

**Comment by rolandkozma** [comment]
Thanks oliemansm! Indeed, it would be great to be able to do it that way, but I'm struggling with the configurations. I asked for help here: 
https://stackoverflow.com/questions/45959234/authentication-in-spring-boot-using-graphql
Could you help me out answering on stackoverflow?

**Comment by rolandkozma** [comment]
Can you give me please a spring/spring-boot solution to have some graphql operation that can be anonymously accessed, while others are secured?
 If I secure the "/graphgl" endpoint with .antMatchers("/graphql").authenticated(), I can use @PreAuthorize annotations on service methods to restrict existing roles, but anonymous users are not allowed access at all.

**Comment by oliemansm** [comment]
Instead of `.antMatchers("/graphql").authenticated()` try to `.antMatchers("/graphql").permitAll()`. You're `@PreAuthorize` annotations should still work while anonymous access is also allowed.

Instead of doing basic auth on the servlet endpoint itself, you can create a mutation to create a token given a username and password, e.g.
```
mutation createSession(input: {username:"foo", password:"bar"}) {
 token
}
```

Have the server generate a JWT token for example for this mutation. Use middleware to add this token in the Authorization header with each GraphQL request. Add a authentication filter in the Spring Security Chain to check the token and load the user in the Security Context. You can specify that the session should be stateless in the security configuration.

I was trying to find an example to answer your stackoverflow question, but couldn't find one yet and hadn't come around to it create one myself. Does the above help you?

Best,
Michiel

Groet,
Michiel
________________________________

**Comment by rolandkozma** [comment]
Thank you very much for your suggestions! I'm going to try to implement them right away. I'll let you know about my progress.

**Comment by rolandkozma** [comment]
I'm happy to let you know that we solved the issue. The filter was not even needed. Spring is able to restore the session from redis if it is persisted as Spring expects. I answered my question on stackoverflow. Thanks a lot for your suggestions! 
Is it a best practice to have the login/logout operations as mutations?

**Comment by oliemansm** [comment]
Glad to hear it! I think it is, yeah.

Best,
Michiel
________________________________
