### ISSUE TITLE
The usage of starter modules

### ISSUE THREAD

**Issue by hfye** [graphql-java/graphql-spring-boot#42]
Hi,

Can I just add these two dependencies instead of starter to the pom.xml?

graphiql-spring-boot-autoconfigure
graphql-spring-boot-autoconfigure

What's the usage of another two starter modules:
graphiql-spring-boot-starter
graphql-spring-boot-starter

Thanks.

**Comment by oliemansm** [comment]
Hi hfye,

See https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-developing-auto-configuration.html#boot-features-custom-starter for background information on creating your own starter and why it's convention to separate these. In short, the starter module is intended to provide the necessary dependencies to work with the library. 

Haven't checked the use in this project actually if it's indeed being used as such or not. Even though it might not be used that way right now, that might change in the future. So if you would skip the starters for now and add the autoconfigure dependencies directly you might run into problems in the future when those are upgraded. Since they're empty jars, they don't do much harm anyway, so I would just use the starters.

Best,
Michiel

**Comment by apottere** [comment]
The main reason there are two dependencies for each starter is because that's how [the abandoned project this was forked from](https://github.com/oembedler/graphql-spring-boot) was set up.  Since the starter dependency doesn't include any other libraries it isn't actually necessary, but there also isn't really an incentive to change it.
