### ISSUE TITLE
Add samples of how to test Graph QL Controller layer 

### ISSUE THREAD

**Issue by AUserNamedE** [graphql-java/graphql-spring-boot#46]
Hi

I want to create an integration test for the graphQL processing layer mocking the underlying services. That is, test it like any other controllers, and post proper graphQL queries. I tried to get it working using WebMvcTest or SpringBootTest but was not successful. I think a sample will be very useful. 

@RunWith(SpringRunner.class)
@WebMvcTest
@AutoConfigureMockMvc(secure=false)
public class GraphQLControllerTest {
  @Autowired
  WebApplicationContext applicationContext;

  @Autowired
  MockMvc mockMvc;
	
  @MockBean
  MyService mockMyService;
....
`

**Comment by oliemansm** [comment]
Would like that as well

**Comment by sazzer** [comment]
If it helps, I'm testing mine using Spring Test, Spring Boot Starter Test,
and hard-coding GraphQL Queries in my test code which I'm sending using the
`TestRestTemplate` class that Spring provides. (I'm also using Cucumber to
write the tests, but that's not really relevant here)

**Comment by oliemansm** [comment]
That certainly helps, but I'm struggling specifically with the part how to ensure that not my entire context is auto loaded, and that only the relevant GraphQL part is loaded. How did you solve that? Do you include a specific configuration for your test, or do you exclude all the stuff you don't need?

The other stuff (Jpa, MVC controllers, etc) which I don't need for the GraphQL part takes too long to load for my tests, so I'm looking for a way to cut that load time considerably.

**Comment by sazzer** [comment]
To be honest, at that level of testing I do load my entire context and I'm
using an embedded MongoDB Database as the backend. I'm then testing
*everything*.
Previously, not with GraphQL, I've used Spring Profiles to make the bits I
want to replace in a "prod" profile, run my tests in a "test" profile, and
add a configuration class that replaced them with EasyMock versions. That
works well enough, but can be a bit of work to maintain.

**Comment by oliemansm** [comment]
The maintenance of that is indeed a big downside.. I'll stick with the entire context for now, thanks!

**Comment by dsebastien** [comment]
How do you maintain the test queries? As escaped Strings in code or within separate files?
I'd like to put my test queries in dedicated (.graphql) files, for example:

```
mutation {
  createThing(name: "foo", description: "bar") {
    uuid,
    name,
    description
  }
}
```

And an easy way in Java to convert the above to what I actually need to send over the wire:
```
{
  "query": "mutation {\n  createThing(name: \"e\", description: \"cool\") {\n    uuid,\n    name,\n    description\n  }\n}",
  "variables": null
}
```

Has anyone done this yet? :)

**Comment by dsebastien** [comment]
Here's my take on the above, in caase anyone's interested: https://medium.com/@dSebastien/graphql-api-integration-tests-in-a-spring-boot-2-x-kotlin-application-5840d3c5d66f
HTH! :)

**Comment by tamland** [comment]
The issue seems to be that MockMvc isn't working with servlets. A workaround is to disable the servlet mapping and add spring wrapper controller like so:

````
@RestController
public class GQLController {

    @Autowired
    private GraphQLServlet graphQLServlet;

    @RequestMapping("graphql")
    public void graphql(HttpServletRequest request, HttpServletResponse response) throws Exception {
        graphQLServlet.service(request, response);
    }
 }
````

**Comment by oliemansm** [comment]
With a little help from the example of @dsebastien and the effort of @mxab we added the first version of [graphql-spring-boot-starter-test](https://github.com/graphql-java/graphql-spring-boot/tree/master/graphql-spring-boot-starter-test) that should help with writing your tests. See [example-graphql-tools](https://github.com/graphql-java/graphql-spring-boot/tree/master/example-graphql-tools) for example how to use it.

**Comment by neerajsu** [comment]
I had an issue with using GraphQLTestTemplate provided with spring-boot-starter-test where my tests were `@Transactional`.

If I annotated tests with `@Transactional` and say I created a new record in a table (Obviously it wasn't committed yet as the test execution hasn't completed). Then I invoked a query using GraphQLTestTemplate, the resolvers were not able to see the created record. This is because GraphQLTestTemplate uses TestRestTemplate which invokes a http call, so when the execution comes to the resolvers a new Transaction is created, and this transaction doesn't have access to the entities created before.

If I get rid of `@Transactional` from test, then the test works fine, as the record is actually committed into the DB. But the side effect is that test records are now in the DB, and other integration tests running might break. 

So, to support transactional integration testing I created a custom Tester [here](https://github.com/graphql-java-kickstart/graphql-spring-boot/issues/398#issuecomment-618107797). You just need to autowire it into your test and use it. It usage is exactly the same as `GraphQLTestTemplate`, except it will ensure to maintain the Transactional context of test cases when annotated with `@Transactional`.

Although the issue is closed, I added this comment in case someone else comes looking for a similar requirement just like I did.
