### ISSUE TITLE
Store locally graphiql cdn sources

### ISSUE THREAD

**Issue by gibert1993** [graphql-java/graphql-spring-boot#51]
Can you add an ability to store graphiql sources (js/css) locally but not download from cdn? Or write a little guide on how to do it now?

**Comment by liqweed** [comment]
We intend to deploy graphql-java on-prem behind firewalls that don't allow internet access. Loading the resources from CDN wouldn't work under these requirements.

**Comment by apottere** [comment]
@gibert1993 @liqweed would it be possible to load resources from an internal CDN instead of bundling them with the project?  It would be nice to be able to swap out versions of graphiql with an application property, but that's not possible if the files are bundled with the spring-boot starter.

e.g. A spring property could be used to pass the CDN hostname instead of using cloudflare.

**Comment by liqweed** [comment]
@apottere How about using [WebJars](https://www.webjars.org/) for that? That way the versions are maintained in Gradle and there would be no need to setup a local CDN just to serve these few files:

```
compile 'org.webjars.npm:graphiql:0.11.5'
compile 'org.webjars.npm:react:15.6.2'
compile 'org.webjars.npm:react-dom:15.6.2'
compile 'org.webjars.npm:whatwg-fetch:2.0.4'
compile 'org.webjars.npm:es6-promise:4.2.4'
```

As a bonus, the graphiql JS & CSS are a part of the same distribution so their version would never go out of sync.
