### ISSUE TITLE
Spring Transactions in GraphQLResolver methods not working

### ISSUE THREAD

**Issue by arcuri82** [graphql-java/graphql-spring-boot#92]
Hi,
  I am starting using GraphQL with Spring, but having an issue in which transactions started on the  GraphQLResolver do not seem to be joined by the transactional calls of injected beans (using JPA with Hibernate). 

For example, assume a Post entity with a lazily fetched list of Comment. A  GraphQLResolver<PostEntity>  for the comments could be (in Kotlin):

```
@Transactional
 fun getComments(post: PostEntity): List<CommentEntity> {

       println("------- TRANSACTION: " + TransactionSynchronizationManager.isActualTransactionActive())
       val reloaded = postRepository.findById(post.id).get()
       return reloaded.comments

        //return commentRepository.findByParentPostId(post.id!!)
}
```
when that method is called, a transaction is started (the print method is `true`), but then ending in a  `java.util.concurrent.CompletionException: org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: org.tsdes.advanced.graphql.database.entity.PostEntity.comments, could not initialize proxy - no Session` when the execution does reach `reloaded.comments`.
Somehow, the `findById` does not see to join the transaction.

This seems the same kind of problem reported here:  [https://stackoverflow.com/questions/48037601/lazyinitializationexception-with-graphql-spring#]( https://stackoverflow.com/questions/48037601/lazyinitializationexception-with-graphql-spring#)

 The workaround is to do not rely on GraphQLResolver being transactional, and put all transactional code in a separated injected bean (e.g, the commented out last line in the code snippet).

But I am wondering, is anything special on on how those GraphQLResolver beans are created? Any idea or solution on why this is not working? Anyway, could be good to mention this issue (if it is indeed an issue and not something silly I misunderstood) in the documentation (I guess I am not the first one trying to use GraphQL with JPA).

Btw, full code example (with running tests) can be found [here](https://github.com/arcuri82/testing_security_development_enterprise_systems/blob/master/advanced/graphql/database/src/main/kotlin/org/tsdes/advanced/graphql/database/resolver/PostResolver.kt)

**Comment by oliemansm** [comment]
@apottere Do you have an idea why this is off the top of the head or does this need to be investigated?

**Comment by apottere** [comment]
I haven't run into this issue myself, and I don't use transactions at all, so I'm not sure what's causing this off the top of my head.  It might have something to do with the way we call reflective methods on the object - AFAIK the transactional annotation works by creating a proxy to the real bean that starts the transaction.  It could be we're somehow bypassing the proxy when we invoke the method?  I would be surprised if this were the case but I can't think of anything else that would be causing it.

**Comment by arcuri82** [comment]
hi,
 the transaction seems created (`isActualTransactionActive()` returns true), but somehow it is still not working. Maybe the injected beans do work on a different DB session? but that seems like very low-level details of Spring JPA which is way beyond my knowledge :(

**Comment by apottere** [comment]
Ah, sorry, I missed the part about the transaction being created.  In that case I'm really not sure what would be causing it to fail if the resolver is transactional but succeed if the service is transactional.

**Comment by KammererTob** [comment]
I am the creator of the mentioned stackoverflow question and i might be able to shed some light (but be aware that i myself am no expert on this matter).

I assume that you are querying for some properties of the comments, right? So what happens is that your `getComments` returns a **proxy** hibernate object (because it is lazily fetched) and your transaction is getting closed after the return. Then as soon as graphlql tries to resolve the properties defined in the query it tries to access a property of the proxy and thus triggers it to be resolved. This throws the exception, because it is no longer inside the initial transaction.

Could you try to do a `comments.size()` before returning the list? If that works, then it kind of confirms my suspicion.

**Comment by arcuri82** [comment]
Hi,
  you are right! that worked. So this is something related to Hibernate, and not really related to GraphQL in the end... I am sorry. Many thanks for your time

**Comment by Thinkenterprise** [comment]
@arcuri82 @KammererTob @apottere A few more thoughts and information on that.
I think in a mutation resolver it could be necessary to set a transaction on a method, because on the one hand the state is changed and on the other hand several database calls can take place which have to be packed in a transaction bracket. So I tried ``@Transaction`` again and it **works**!!. The database is rolled back.
```
@Component
public class RootMutationResolver implements GraphQLMutationResolver {
	     
    @Transactional(rollbackFor = DataIntegrityViolationException.class)
    public Route createRoute(String flightNumber) {
    	Route route = new Route(flightNumber);
        routeRepository.save(route);
       throw new DataIntegrityViolationException("Test");
    }
}
```
